"""empty message

Revision ID: 55107a51d711
Revises: 0d130d2823b2
Create Date: 2025-03-03 13:42:19.355096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55107a51d711'
down_revision = '0d130d2823b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_username_key', type_='unique')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('user_username_key', ['username'])

    # ### end Alembic commands ###
